import rawPapers from "@/data/papers.json";

/**
 * One paper in the fake journal archive. The corpus is generated by
 * `scripts/generate-corpus.mjs`; this module is the only place the rest of the
 * app reads it from.
 */
export type Paper = {
  id: string;
  title: string;
  authors: string[];
  affiliation: string;
  section: string;
  sectionCode: string;
  journal: string;
  volume: number;
  issue: number;
  doi: string;
  publishedAt: string;
  keywords: string[];
  abstract: string;
  firstPage: number;
  pageCount: number;
  pageRange: string;
  fileName: string;
  fileSize: number;
};

/** Newest first, matching the order the generator wrote them in. */
export const papers = rawPapers as Paper[];

export const JOURNAL_NAME = papers[0].journal;
export const JOURNAL_ABBREV = "MJAS";

export const DEFAULT_PAGE_SIZE = 10;

export type PaperPage = {
  items: Paper[];
  page: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
  /** 1-based index of the first and last item on this page. */
  firstIndex: number;
  lastIndex: number;
  hasPrevious: boolean;
  hasNext: boolean;
};

export function totalPages(pageSize = DEFAULT_PAGE_SIZE): number {
  return Math.max(1, Math.ceil(papers.length / pageSize));
}

/**
 * Reads a `?page=` value. Anything unparseable or out of range clamps to a real
 * page rather than erroring, which is how most archives behave.
 */
export function parsePageParam(
  value: string | string[] | undefined,
  pageSize = DEFAULT_PAGE_SIZE,
): number {
  const raw = Array.isArray(value) ? value[0] : value;
  const parsed = Number.parseInt(raw ?? "1", 10);
  if (!Number.isFinite(parsed)) return 1;
  return Math.min(Math.max(parsed, 1), totalPages(pageSize));
}

export function paginatePapers(
  page: number,
  pageSize = DEFAULT_PAGE_SIZE,
): PaperPage {
  const pages = totalPages(pageSize);
  const current = Math.min(Math.max(page, 1), pages);
  const start = (current - 1) * pageSize;
  const items = papers.slice(start, start + pageSize);

  return {
    items,
    page: current,
    pageSize,
    totalItems: papers.length,
    totalPages: pages,
    firstIndex: start + 1,
    lastIndex: start + items.length,
    hasPrevious: current > 1,
    hasNext: current < pages,
  };
}

export function getPaperById(id: string): Paper | undefined {
  return papers.find((paper) => paper.id === id);
}

export function getPaperByFileName(fileName: string): Paper | undefined {
  return papers.find((paper) => paper.fileName === fileName);
}

const MONTHS = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

/** Formatted without `Intl` so server and client always agree. */
export function formatPublishedDate(iso: string): string {
  const [year, month, day] = iso.slice(0, 10).split("-");
  return `${Number(day)} ${MONTHS[Number(month) - 1]} ${year}`;
}

export function formatFileSize(bytes: number): string {
  return `${(bytes / 1024).toFixed(1)} KB`;
}

export function formatAuthors(authors: string[], max = 3): string {
  if (authors.length <= max) return authors.join(", ");
  return `${authors.slice(0, max).join(", ")} et al.`;
}
